### ISSUE TITLE
Option preserveMediaQueries also for external css files

### ISSUE THREAD

**Issue by Spica2** [andrewrk/juice#10]
Option preserveMediaQueries also for external css files. Is that possible or planned in near future?

**Comment by andrewrk** [comment]
maybe @jrit has an opinion on this

**Comment by jrit** [comment]
I've thought about it. There really just needs to be an option to take the CSS from external stylesheets and inject them into `<style>` as a first step. If that was setup properly I think the existing `preserveMediaQueries` could stay the way it is.

**Comment by andrewrk** [comment]
I'm not using this module in production anymore - I'm firmly in the "maintainer" role now. So whoever wants this feature has to make it happen.

**Comment by Spica2** [comment]
I have a workflow, that first injects the styles into style-tag. But it would be easier to have it as an option. Especialy when you work with css frameworks.

**Comment by jrit** [comment]
@Spica2 do you want to try updating juice so it has this option?

**Comment by Spica2** [comment]
Are you asking me, if I am gonna do that? Thats far out of my capabilities.

**Comment by jrit** [comment]
@Spica2 ok, I may do it when I have some free time
