### ISSUE TITLE
add option for keeping !important

### ISSUE THREAD

**Issue by k7y6t5** [andrewrk/juice#12]
It looks like my !important rules are getting stripped out. This is mainly a problem with overriding iOS blue links. Any chance of adding an option to keep them in?

BTW I'm using this via gulp-inline-css.

**Comment by andrewrk** [comment]
Sounds like something that should be fixed.

I'm acting as a maintainer for this module but I don't have the proper use case to do feature development. So I'd be happy to merge a pull request that fixed this and included a test to make sure it works, but I won't be personally developing the fix.
