### ISSUE TITLE
Option to preserve self closing tags

### ISSUE THREAD

**Issue by bensreed** [andrewrk/juice#14]
I'm using juice via gulp-inline-css and found that when inlining it replaces `<br />` with `<br>`. Same with all self closing tags — img, meta, etc. Is there any way to allow this option or set as default?

Most email frameworks and kickstarts use XHTML 1.0 strict and this would help everything validate.

**Comment by andrewrk** [comment]
This module is actively maintained but not actively developed. Which means, issues don't get fixed automatically for you, but if you make a pull request I will look at it and give feedback, merge, release, etc.

**Comment by bensreed** [comment]
Fair enough. Thanks for the reply.
