### ISSUE TITLE
feature: possibility to bypass any style or link on the inline process.

### ISSUE THREAD

**Issue by jpsc** [andrewrk/juice#25]
I would be nice to have the possibility to bypass any style or link on the inline.
When building some newsletters templates its sometimes unnecessary and unwanted that all the styles are inline.

Something like this:

```
<!-- external styles -->
<link rel="stylesheet" data-ignore="ignore"  href="style.css" />

<!-- embedded styles -->
<style data-ignore="ignore"></style>
```

Idea from [here](https://github.com/yargalot/Email-Builder#documentation).

What do you think ?

**Comment by jlank** [comment]
+1 here.  This is useful for retaining certain assets like Google Fonts.

**Comment by bahamagician** [comment]
Has there been any developments on this?

**Comment by jpsc** [comment]
No longer relevant
